#!/usr/bin/bash

# Install ZSH and run initial config wizard
if ! [ $(which zsh) ]; then
	echo "Press enter to install zsh"
	read
	sudo apt install zsh -y
	
	echo "Press enter to install oh-my-zsh"
	read
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

	#Change default shell to zsh
	echo "Press enter to change zsh to your default shell"
	chsh -s $(which zsh)
else
	echo "zsh already installed"
fi

# Install Fonts for PowerLevel10K
if ! [ ~/.fonts ]; then
	mkdir ~/.fonts
else
	echo "Font directory exists"
fi

if ! [[ -n $(find ~/.fonts -name "MesloLGS*") ]]; then
	cp ../fonts/* ~/.fonts
	sudo fc-cache -f -v
	echo "Go to Terminal -> Preferences and set the custom font to any MesloLGS font. Press enter when done."
	read
else
	echo "Fonts already installed"
fi

# Install PowerLevel10K for OhMyZSH

if ! [ ~/.oh-my-zsh/custom/themes/powerlevel10k ]; then
	echo "PowerLevel10k already installed"
	read
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
else
	echo "You already have PowerLevel10k Installed"
fi
