#!/usr/bin/bash

# Install ZSH and run initial config wizard
if ! [ $(which zsh) ]; then
	echo "Press enter to install zsh"
	read
	sudo apt install zsh -y
	
	echo "Press enter to install oh-my-zsh"
	read
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

	#Change default shell to zsh
	echo "Press enter to change zsh to your default shell"
	chsh -s $(which zsh)
else
	echo "zsh already installed"
fi

# Install Fonts for PowerLevel10K
if ! [ ~/.fonts ]; then
	mkdir ~/.fonts
else
	echo "Font directory exists"
fi

if ! [[ -n $(find ~/.fonts -name "MesloLGS*") ]]; then
	cp ../fonts/* ~/.fonts
	sudo fc-cache -f -v
	echo "Go to Terminal -> Preferences and set the custom font to any MesloLGS font. Press enter when done."
	read
else
	echo "Fonts already installed"
fi

# Install PowerLevel10K for OhMyZSH

if ! [ ~/.oh-my-zsh/custom/themes/powerlevel10k ]; then
	echo "Press enter to install PowerLevel10k"
	read
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
else
	echo "PowerLevel10k already installed"
fi

# Install ZSH Plugins
if ! [ ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
	echo "Press enter to install Zsh-Autosuggestions"
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
else
	echo "zsh-autosuggestions already installed"
fi

if ! [ ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
	echo "Press enter to install zsh-syntax-highliting"
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
	echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
	source ./zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
	echo "zsh-syntax-highlighting already installed"
fi

# Copy contents of git zshrc into machine zshrc
echo "Press enter to update and refresh .zshrc"
read
> ~/.zshrc
cat ../dotfiles/zshrc >> ~/.zshrc
