#!/usr/bin/bash

# Install ZSH and run initial config wizard
if ! [ $(which zsh) ]; then
	echo "Press enter to install zsh"
	read
	sudo apt install zsh -y
	
	echo "Press enter to install oh-my-zsh"
	read
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

	#Change default shell to zsh
	echo "Press enter to change default shell. This will log you out for the changes to take effect."
	chsh -s $(which zsh)
	pkill -u $(whoami)
else
	echo "zsh already installed"
fi
